C#&ASP.NET/EasyMeal/WebApplication/UserInterfaceCustomer/Controllers/DishController.cs
using DomainServices.Repositories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using UserInterfaceCustomer.Models.ViewModels;

namespace UserInterfaceCustomer.Controllers
{
    [Authorize]
    public class DishController : Controller
    {
        private IDishRepository repository;
        private ICustomerRepository customerRepository;


        public DishController(IDishRepository repo, ICustomerRepository cRepo)
        {
            repository = repo;
            customerRepository = cRepo;
        }

        public ViewResult List(string category)
        {
            ViewBag.Diet = customerRepository.GetCustomerByName(User.Identity.Name).DieteryRestriction;
            return View(new DishListViewModel
            {
                Dishes = repository.Dishes.Where(d =>
                    d.Type == "Hoofdgerecht" && (category == null || d.Diet == category)),
                CurrentCategory = category

            });
        }
    }
}

C#&ASP.NET/EasyMeal/WebApplication/UserInterfaceCustomer/ViewComponents/NavigationMenuViewComponent.cs
using DomainServices.Repositories;
using Microsoft.AspNetCore.Mvc;
using System.Linq;

namespace UserInterfaceCustomer.ViewComponents
{
    public class NavigationMenuViewComponent : ViewComponent
    {
        private IDishRepository repository;

        public NavigationMenuViewComponent(IDishRepository repo)
        {
            repository = repo;
        }

        public IViewComponentResult Invoke()
        {
            ViewBag.SelectedCategory = RouteData?.Values["category"];
            return View(repository.Dishes
                .Select(x => x.Diet)
                .Distinct()
                .OrderBy(x => x));
        }
    }
}

C#&ASP.NET/EasyMeal/WebApplication/UserInterfaceCustomer/Views/Dish/List.cshtml
@model DishListViewModel

@{
    Layout = "_CustomerLayout";
}

<div class="row">
    <div id="categories" class="col-sm-12">
        @await Component.InvokeAsync("NavigationMenu")
    </div>
    
</div>

<div class="row">
    <div id="dishes" class="col-sm-12">
        <div class="container">
            @foreach (var d in Model.Dishes)
            {
                if (d.Diet == ViewBag.Diet)
                {
                    <div id="dish" class="col-sm-4">
                        @Html.Partial("DishSummary", d)
                    </div>
                }
                else
                {
                    <div id="dish" class="col-sm-4" style="background-color:darkgray">
                        @Html.Partial("DishSummary", d)
                    </div>
                }
                
            }
        </div>
    </div>
</div>