C#&ASP.NET/EasyMeal/WebApplication/UserInterfaceCustomer/Controllers/CartController.cs
using Domain.CustomerDomain;
using DomainServices.Repositories;
using Infrastructure.Extensions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using UserInterfaceCustomer.Models.ViewModels;


namespace UserInterfaceCustomer.Controllers
{
    [Authorize]
    public class CartController : Controller
    {
        private IMealRepository repository;
        public CartController(IMealRepository repo)
        {
            repository = repo;

        }
        public ViewResult Index(string returnUrl)
        {
            return View(new CartIndexViewModel
            {
                Cart = GetCart(),
                ReturnUrl = "/Meal/List"
            });
        }

        public RedirectToActionResult AddToCart(int mealId, string returnUrl)
        {
            Meal meal = repository.Meals.First(m => m.MealId == mealId);

            if (meal != null)
            {
                Cart cart = GetCart();
                cart.AddItem(meal);
                SaveCart(cart);
            }
            return RedirectToAction("Index", new { returnUrl });
        }
        public RedirectToActionResult RemoveFromCart(int mealId,
            string returnUrl)
        {
            Meal meal = repository.Meals
                .FirstOrDefault(p => p.MealId == mealId);
            if (meal != null)
            {
                Cart cart = GetCart();
                cart.RemoveLine(meal);
                repository.DeleteMeal(meal.MealId);
                SaveCart(cart);
            }
            return RedirectToAction("Index", new { returnUrl });
        }

        private Cart GetCart()
        {
            Cart cart = HttpContext.Session.GetJson<Cart>("Cart") ?? new Cart();
            return cart;
        }
        private void SaveCart(Cart cart)
        {
            HttpContext.Session.SetJson("Cart", cart);
        }
    }
}

C#&ASP.NET/EasyMeal/WebApplication/UserInterfaceCustomer/Controllers/DishController.cs
using DomainServices.Repositories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using UserInterfaceCustomer.Models.ViewModels;

namespace UserInterfaceCustomer.Controllers
{
    [Authorize]
    public class DishController : Controller
    {
        private IDishRepository repository;
        private ICustomerRepository customerRepository;


        public DishController(IDishRepository repo, ICustomerRepository cRepo)
        {
            repository = repo;
            customerRepository = cRepo;
        }

        public ViewResult List(string category)
        {
            ViewBag.Diet = customerRepository.GetCustomerByName(User.Identity.Name).DieteryRestriction;
            return View(new DishListViewModel
            {
                Dishes = repository.Dishes.Where(d =>
                    d.Type == "Hoofdgerecht" && (category == null || d.Diet == category)),
                CurrentCategory = category

            });
        }
    }
}

C#&ASP.NET/EasyMeal/WebApplication/UserInterfaceCustomer/Controllers/OrderController.cs
using Domain.CustomerDomain;
using DomainServices.Repositories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Linq;


namespace UserInterfaceCustomer.Controllers
{
    [Authorize]
    public class OrderController : Controller
    {
        private IOrderRepository repository;
        private ICustomerRepository customerRepository;
        private Cart cart;

        public OrderController(IOrderRepository repoService, ICustomerRepository custRepo, Cart cartService)
        {
            repository = repoService;
            customerRepository = custRepo;
            cart = cartService;
        }

        public ViewResult Checkout()
        {
            ViewBag.Meals = cart.Lines;
            return View(new Order
            {
                Meals = cart.Lines
            });
        }


        public ViewResult Index() => View("Index");

        [HttpPost]
        public IActionResult Checkout(Order order)
        {
            if (!cart.Lines.Any())
            {
                ModelState.AddModelError("", "Sorry, je winkelmandje is leeg!");
            }

            if (!cart.IsValid())
            {
                ModelState.AddModelError("", "Je hebt nog niet voor minimaal 4 dagen in de werkweek besteld");
            }
            if (ModelState.IsValid)
            {
                repository.SaveOrder(order);
                Customer customer = customerRepository.GetCustomerByName(User.Identity.Name);
                customer.Orders.Add(order);
                cart.Clear();
                return RedirectToAction(nameof(Completed));
            }
            else
            {
                return View(order);
            }
        }
        public IActionResult Completed()
        {
            cart.Clear();
            return RedirectToAction("Index", "Customer");
        }
    }
}

C#&ASP.NET/EasyMeal/WebApplication/UserInterfaceCustomer/Views/Cart/Index.cshtml
@model CartIndexViewModel

@{
    Layout = "_CustomerLayout";
}

<h2>Winkelmandje</h2>
<table class="table table-bordered table-striped">
    <thead>
    <tr>
        <th>Dag van de week</th>
        <th class="text-right">Prijs</th>
        <th class="text-right">Acties</th>
    </tr>
    </thead>
    <tbody>
    @foreach (var line in Model.Cart.Lines) {
        <tr>
            <td class="text-left">@line.GetDutchDayOfWeek()</td>
            <td class="text-right">@line.TotalPrice.ToString("c")</td>
            <td>
                <form asp-action="RemoveFromCart" method="post">
                    <input type="hidden" name="MealIds"
                           value="@line.MealId" />
                    <input type="hidden" name="returnUrl"
                           value="@Model.ReturnUrl" />
                    <button type="submit" class="btn btn-sm btn-danger">
                        Verwijder
                    </button>
                </form>
            </td>
        </tr>
    }
    </tbody>
    <tfoot>
    <tr>
        <td colspan="3" class="text-left">Totaalbedrag: @Model.Cart.ComputeTotalValue().ToString("c")</td>
       
    </tr>
    </tfoot>
</table>
<div class="text-center">
    <a class="btn btn-primary" asp-action="List" asp-controller="Dish">Shop verder</a>
    <a class="btn btn-primary" asp-action="Checkout" asp-controller="Order">
        Bestellen
    </a>
</div>