C#&ASP.NET/EasyMeal/WebApplication/UserInterfaceCustomer/Controllers/CustomerController.cs
using Domain.CustomerDomain;
using DomainServices.Repositories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Linq;

namespace UserInterfaceCustomer.Controllers
{
    [Authorize]
    public class CustomerController : Controller
    {
        private ICustomerRepository repository;
        private IOrderRepository orderRepository;
        private IMealRepository mealRepository;

        public CustomerController(ICustomerRepository repo, IOrderRepository orderRepo, IMealRepository mealRepo)
        {
            repository = repo;
            orderRepository = orderRepo;
            mealRepository = mealRepo;
        }


        public IActionResult Index()
        {
            Customer customer = repository.GetCustomerByName(User.Identity.Name);
            ViewBag.CanOrder = true; //aanpassen

            customer.Orders.Add(new Order { Meals = mealRepository.Meals.Where(m => m.DateOfOrder.Month == DateTime.Today.Month).ToList() });
            var dept = customer.GetDeptByMonth(DateTime.Today.Month);

            ViewBag.Dept = dept;
            return View(customer);
        }


        public IActionResult Months()
        {
            Customer customer = repository.GetCustomerByName(User.Identity.Name);
            customer.Orders.Add(new Order { Meals = mealRepository.Meals.Where(m => m.DateOfOrder.Month == DateTime.Today.Month).ToList() });
            var quantityDiscount = false;
            var BDdiscount = false;
            var mealscounts = 0;
            var orders = orderRepository.Orders;
            var meals = mealRepository.Meals.ToList();
            foreach (var order in orders)
            {
                meals.AddRange(order.GetMealsWithMonth(DateTime.Today.Month));
            }

            foreach (var meal in meals)
            {
                if (customer.Birthdate.Day == meal.DateOfOrder.Day &&
                    customer.Birthdate.Month == meal.DateOfOrder.Month)
                {
                    BDdiscount = true;
                }
                else
                {
                    mealscounts++;
                }
            }

            if (mealscounts >= 15)
            {
                quantityDiscount = true;
            }

            ViewBag.BDdiscount = BDdiscount;
            ViewBag.Qdiscount = quantityDiscount;
            ViewBag.Meals = meals;
            ViewBag.Dept = customer.GetDeptByMonth(DateTime.Today.Month);

            return View();
        }

    }
}

C#&ASP.NET/EasyMeal/WebApplication/UserInterfaceCustomer/Controllers/MealController.cs
using Domain.CookDomain;
using Domain.CustomerDomain;
using DomainServices.Repositories;
using Infrastructure.Extensions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Linq;
using UserInterfaceCustomer.Models.ViewModels;

namespace UserInterfaceCustomer.Controllers
{
    [Authorize]
    public class MealController : Controller
    {
        private IDishRepository repository;
        private IMealRepository mealRepository;
        private IQueryable<Dish> Dishes;

        public MealController(IDishRepository repo, IMealRepository mealrepo)
        {
            repository = repo;
            mealRepository = mealrepo;
            Dishes = repository.Dishes;
        }


        public IActionResult Details(int dishId)
            => View(new NewMealViewModel
            {
                CurrentDish = Dishes.Single(d => d.DishId == dishId).Name,
                CategoryDessertDishes = Dishes.Single(d => d.Diet == (Dishes.Single(p => p.DishId == dishId).Diet) && d.Type == "Nagerecht").Name.ToString(),
                CategoryPreDishes = Dishes.Single(d => d.Diet == (Dishes.Single(p => p.DishId == dishId).Diet) && d.Type == "Voorgerecht").Name.ToString()
            });

        [HttpPost]
        public IActionResult Details(NewMealViewModel mealVM)
        {

            if (ModelState.IsValid)
            {
                decimal preDishPrice = Dishes.Single(d => d.Name == mealVM.StarterDish).Price;
                decimal dessertDishPrice = Dishes.Single(d => d.Name == mealVM.DessertDish).Price;
                decimal mainDishPrice = Dishes.Single(d => d.Name == mealVM.CurrentDish).Price;

                var meal = new Meal
                {
                    MainDish = Dishes.First(d => d.Name == mealVM.CurrentDish).DishId,
                    StarterDish = Dishes.First(d => d.Name == mealVM.StarterDish).DishId,
                    DessertDish = Dishes.First(d => d.Name == mealVM.DessertDish).DishId,
                    DateOfOrder = DateTime.Today.GetDateByDay(mealVM.Day),
                    Size = mealVM.Size,
                    TotalPrice = dessertDishPrice + preDishPrice + mainDishPrice
                };

                meal.SetTotalPrice(mealVM.Size);

                if (meal.IsValid())
                {
                    mealRepository.SaveMeal(meal);
                    return View("Overview", meal);
                }
            }
            ModelState.AddModelError("", "Je hebt niet een voorgerecht of nagerecht gekozen");
            return View(mealVM);

        }
    }
}

C#&ASP.NET/EasyMeal/WebApplication/UserInterfaceCustomer/ViewComponents/CartSummaryViewComponent.cs
using Domain.CustomerDomain;
using Microsoft.AspNetCore.Mvc;

namespace UserInterfaceCustomer.ViewComponents
{
    public class CartSummaryViewComponent : ViewComponent
    {
        private Cart cart;
        public CartSummaryViewComponent(Cart cartService)
        {
            cart = cartService;
        }
        public IViewComponentResult Invoke()
        {
            return View(cart);
        }
    }
}

C#&ASP.NET/EasyMeal/WebApplication/UserInterfaceCustomer/Views/Shared/DishSummary.cshtml
@model Dish
<div class="polaroid">
    @if (@Model.Image != null)
    {
        <img src="data:image/jpg;base64,@Convert.ToBase64String(@Model.Image)">
    }
    else
    {
        <img src="/images/frontpage.jpg" alt="Norway" style="width: 100%">

    }
    <div class="container">
        <p>@Model.Name</p>
        <span class="badge badge-pill badge-primary">
            <small>@Model.Price.ToString("c")</small>
        </span>
        <a class="btn btn-block" asp-action="Details" asp-controller="Meal" asp-route-dishId="@Model.DishId">
            Details
        </a>
    </div>
</div>

C#&ASP.NET/EasyMeal/WebApplication/UserInterfaceCustomer/Views/Shared/_CustomerLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
    <script src="https://kit.fontawesome.com/a076d05399.js"></script>
    <link rel="stylesheet" asp-href-include="css/Styles.css" />
    <link rel="stylesheet" asp-href-include="/lib/fontawesome/css/*.css" />
</head>
<body>


<nav id="nav" class="navbar navbar-inverse bg-inverse" role="navigation">
    <div class="container-fluid">
    <div class="navbar-header">
        <a class="navbar-brand" href="#">EasyMeal</a>
    </div>
    <ul class="nav navbar-nav">
        <li ><a asp-action="Index" asp-controller="Customer">Dashboard</a></li>
        <li ><a asp-action="Months" asp-controller="Customer">Maandoverzicht</a></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
        <li>@await Component.InvokeAsync("CartSummary")</li>
        <li><a class="btn btn-sm btn-primary" asp-action="Logout" asp-controller="Account">Log Out</a></li>
    </ul>
   
    </div>
</nav>

<div>
    <main>
        @if (TempData["message"] != null)
        {
            <div class="alert alert-success">@TempData["message"]</div>
        }
        @RenderBody()

    </main>
</div>

</body>
</html>

C#&ASP.NET/EasyMeal/WebApplication/UserInterfaceCustomer/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <title>@ViewBag.Title</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
    <link rel="stylesheet" asp-href-include="css/Styles.css" />
    <link rel="stylesheet" asp-href-include="/lib/fontawesome/css/*.css" />
</head>
<body>

<nav id="nav" class="navbar navbar-inverse">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href="#">EasyMeal</a>
        </div>
        <ul class="nav navbar-nav">
            <li ><a asp-action="Index" asp-controller="Home">Home</a></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
            <li><a asp-action="Register" asp-controller="Account"><span class="glyphicon glyphicon-user"></span> Registreer</a></li>
            <li><a asp-action="Login" asp-controller="Account"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
        </ul>
    </div>
</nav>


    <div class="container">
    <main role="main">
        @RenderBody()
    </main>

    </div>

    <footer>
        <p>FOOTER</p>
    </footer>
</body>
</html>